#! /usr/bin/env bash

# Definicije boja
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

read -p $'\033[1;33mPritisnite [Enter] da bi ste nastavili...\033[0m'
echo "Krećemo..."
sleep 1s

echo -e ${YELLOW}Ažuriranje liste repozitorija...${NC}
sleep 1s
apt update

echo -e ${YELLOW}Dodavanje repozitorija...${NC}
sudo add-apt-repository main
sudo add-apt-repository universe
sudo add-apt-repository restricted
sudo add-apt-repository multiverse

echo -e ${YELLOW}Ažuriranje i nadogradnja...${NC}
apt update && apt upgrade -y

echo -e ${YELLOW}Instalira se apache2, php i mysql${NC}
apt install apache2 php mysql-server -y

echo -e ${YELLOW}Instaliranje php ekstenzija...${NC}
apt install php-zip php-mysql php-mbstring php-curl php-gd php-xml -y 

systemctl enable mysql apache2

apt install zip unzip tree -y

echo -e ${YELLOW}Postavi cgi.fix na 0 u php.ini...${NC}
sed -i 's/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/g' /etc/php/7.2/apache2/php.ini

systemctl restart apache2

echo -e ${YELLOW}Kreiranje phpinfo fajla...${NC}
echo "<?php phpinfo(); ?>" > /var/www/html/info.php
echo "Vasa lamp instalacija je uspesno podesena!" > /var/www/html/index.html

echo -e ${YELLOW}Instaliranje Webmin kontrol panela...${NC}
echo "deb http://download.webmin.com/download/repository sarge contrib" >> /etc/apt/sources.list
apt-key add jcameron-key.asc -y
apt update
apt install webmin -y
sed -i 's/port=10000/port=3000/g' /etc/webmin/miniserv.conf
/etc/init.d/webmin restart



