#!/usr/bin/env bash

# Definicije boja
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Unos neophodnih podataka
echo $'\033[1;33mMolimo vas da unesete osnovne podatke o infra-strukturi:\033[0m '

while true; do
    read -p 'Unesite naziv domena bez protokola (bez http://): ' hostname
    read -p 'Unesite ponovo da bi ste potvrdili: ' hostname2
    [ "$hostname" = "$hostname2" ] && break
    echo -e ${RED}Molimo pokušajte ponovo.${NC}
done

echo
read -p 'Unesite korisničko ime UNIX korisnika: ' unixuser

while true; do
    read -s -p 'Unesite lozinku UNIX korisnika: ' unixpass
    read -s -p 'Unesite ponovo da bi ste potvrdili: ' unixpass2
    [ "$unixpass" = "$unixpass2" ] && break
    echo -e ${RED}Molimo pokušajte ponovo.${NC}
done

echo
echo $'\033[1;33mPodešavanje lozinke za MYSQL root korinkika\033[0m'
while true; do
    read -s -p 'Unesite lozinku za MYSQL root: ' mysqlrpass
    read -s -p 'Unesite ponovo da bi ste potvrdili: ' mysqlrpass2
    [ "$mysqlrpass" = "$mysqlrpass2" ] && break
    echo -e ${RED}Molimo pokušajte ponovo.${NC}
done

echo
echo $'\033[1;33mPodešavanje Email adrese administratora\033[0m'
while true; do
    read -p 'Unesite vašu Email adresu: ' email
    read -p 'Unesite ponovo da bi ste potvrdili: ' email2
    [ "$email" = "$email2" ] && break
    echo -e ${RED}Molimo pokušajte ponovo.${NC}
done

# Početak instalacije
read -p $'\033[1;33mPritisnite [Enter] da bi ste nastavili...\033[0m'
echo "Krećemo..."
sleep 1s

echo -e ${YELLOW}Ažuriranje liste repozitorija...${NC}
sleep 1s
apt update

echo -e ${YELLOW}Dodavanje repozitorija...${NC}
sudo add-apt-repository main
sudo add-apt-repository universe

echo -e ${YELLOW}Ažuriranje i nadogradnja...${NC}
apt update && apt upgrade -y

apt install software-properties-common apt-transport-https -y

echo -e ${YELLOW}Instalira se apache2, php i mysql${NC}
apt install apache2 php mysql-server -y

echo -e ${YELLOW}Instaliranje php ekstenzija...${NC}
apt install php-zip php-mysql php-mbstring php-curl php-gd php-xml php-xmlrpc php-soap php-intl -y 

systemctl enable mysql apache2

apt install zip unzip tree -y

echo -e ${YELLOW}Podešavanja php-a...${NC}
sed -i 's/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/g' /etc/php/7.2/apache2/php.ini
sed -i 's/post_max_size = 8M/post_max_size = 280M/g' /etc/php/7.2/apache2/php.ini
sed -i 's/upload_max_filesize = 2M/upload_max_filesize = 256M/g' /etc/php/7.2/apache2/php.ini
systemctl restart apache2

echo -e ${YELLOW}Kreiranje phpinfo fajla...${NC}
echo "<?php phpinfo(); ?>" > /var/www/html/info.php
echo "Vasa lamp instalacija je uspesno podesena!" > /var/www/html/index.html

# Webmin instalacija
echo -e ${YELLOW}Instaliranje Webmin kontrol panela...${NC}
echo "deb http://download.webmin.com/download/repository sarge contrib" >> /etc/apt/sources.list
apt-key add jcameron-key.asc -y
apt update
apt install webmin -y
sed -i 's/port=10000/port=3000/g' /etc/webmin/miniserv.conf
/etc/init.d/webmin restart

#podešavanje veb servera
cp vhost.conf /etc/apache2/sites-enabled/$hostname.conf
sed -i 's/	ServerName default/	ServerName $hostname/g' /etc/apache2/sites-enabled/$hostname.conf
sed -i 's/	DocumentRoot /var/www/html/	DocumentRoot /var/www/$hostname/g' /etc/apache2/sites-enabled/$hostname.conf
sed -i 's/<Directory /var/www/html>/<Directory /var/www/$hostname>/g' /etc/apache2/sites-enabled/$hostname.conf

# Instalacija Wordpress-a
while true; do
    read -p "Da li želite da instalirate Wordpress? (Da/Ne): " dn
    case $dn in
        [Dd]* )
		
		# Instaliranje faljova
		wget https://sr.wordpress.org/latest-sr_RS.tar.gz
		tar -xzvf latest-sr_RS.tar.gz
		rm -rf /var/www/html
		mv wordpress /var/www
		mv /var/www/wordpress /var/www/$hostname
		chown www-data:www-data -R /var/www/$hostname
		
		systemctl restart apache2
		
echo "Wordpress je instaliran!";
break;;
        [Nn]* ) exit;;
        * ) echo -e ${RED}Molimo vas da odgovorite sa Da ili Ne.${NC};;
    esac
done

# Instalacija SSL sertifikata
while true; do
    read -p "Da li želite da instalirate SSL sertifikat? (Da/Ne): " dn
    case $dn in
        [Dd]* )
		
		# Certbot instalacija
		add-apt-repository ppa:certbot/certbot
		apt update
		apt install python-certbot-apache -y

		# Instalacija Let's encrypt SSL sertifikata
		certbot --apache --non-interactive --agree-tos --domains $hostname --email webmaster@example.com
		
		# Podešavanje Webmin-a
		sed -i 's/keyfile=/etc/webmin/miniserv.pem/keyfile=/etc/letsencrypt/live/$hostname/privkey.pem/g' /etc/webmin/miniserv.conf
		
echo "SSL je instaliran!";
break;;
        [Nn]* ) exit;;
        * ) echo -e ${RED}Molimo vas da odgovorite sa Da ili Ne.${NC};;
    esac
done



